# SITE CONFIGURATION
baseurl: "/"
url: "hackathonsforschools.com"

# THEME-SPECIFIC CONFIGURATION
title: Hackathons For Schools Association                                    # site's title
description: "Official website for the Hackathons For Schools Association. Everything you need to run your own hackathon at your school can be found right here!"      # used by search engines
avatar: assets/img/logo/circle.png                       # Empty for no avatar in navbar
favicon: assets/img/logo/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Getting more 15-18 year olds involved with hackathons! 🔥🎉                                          # Change Blog header text
header_feature_image: assets/img/background.png
footer_text: >
  Made by students, for students

# Blog
excerpt: false                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true

# Features
katex: true                                             # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
